/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_v3_20_cdm_Capabilities320IT */

#ifndef _Included_at_o2xfs_xfs_v3_20_cdm_Capabilities320IT
#define _Included_at_o2xfs_xfs_v3_20_cdm_Capabilities320IT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_v3_20_cdm_Capabilities320IT
 * Method:    createDefault
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_at_o2xfs_xfs_v3_120_cdm_Capabilities320IT_createDefault
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
