/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_v3_10_cdm_PowerSaveChange310IT */

#ifndef _Included_at_o2xfs_xfs_v3_10_cdm_PowerSaveChange310IT
#define _Included_at_o2xfs_xfs_v3_10_cdm_PowerSaveChange310IT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_v3_10_cdm_PowerSaveChange310IT
 * Method:    createDefault
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_at_o2xfs_xfs_v3_110_cdm_PowerSaveChange310IT_createDefault
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
