/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_v3_30_cdm_Signature330IT */

#ifndef _Included_at_o2xfs_xfs_v3_30_cdm_Signature330IT
#define _Included_at_o2xfs_xfs_v3_30_cdm_Signature330IT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_v3_30_cdm_Signature330IT
 * Method:    createDefault
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_at_o2xfs_xfs_v3_130_cdm_Signature330IT_createDefault
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
